name: Build Js
on:
  #  schedule:
  #    # * is a special character in YAML so you have to quote this string
  #    - cron:  '0/15 * * * *'
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i
        working-directory: "#"
      - run: npm run build
        working-directory: "#"

      - name: Commit build
        uses: EndBug/add-and-commit@v9
        with:
          add: ./*.html
          message: "build-commit"
          default_author: github_actions