name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: ./service

    - name: Build
      working-directory: ./service
      run: cargo build
    - name: Copy Executable
      working-directory:
      run: mv ./service/target/debug/service ./exe
    - name: Commit build
      uses: EndBug/add-and-commit@v9
      with:
        add: ./exe
        message: "build-commit"
        default_author: github_actions

